language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:    
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.15/cmake-3.15.0-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.15.0-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.15.0-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - export CXXFLAGS="$CXXFLAGS -std=c++14"
  - mkdir build
  - cd build
  - cmake ..
  - cat Makefile

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - make

after_failure:
     - cat /home/travis/build/johnscape/NeuralNetwork/CMakeFiles/CMakeOutput.log
